name: vgen
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python = 3.10
  - pip
  - numpy = 1.23
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda = 11.8
  - click
  - pygame
  - pyopengl
  - tqdm
  - scipy
  - opencv
  - mrcfile
  - pip:
    - smplx
    - chumpy
