general:
  nb_faces: 1000 # number faces generate
  device: cuda # choice your device for generate face. ("cpu" or "cuda")
  batch_size: 32 # number of visage generate in the same time
  texturing: True # use texture
  view: False # enable view

generator:
  input_folder: None # input folder for load parameter
  zeros: False # zeros for all params not loaded
  animated:
    enable: False # animate a visage
    nb_frames: 100
  shape:
    params: [300, -2, 2] # Shape parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. default : sum(nX)==300
    fixed: False # fixed the same shape for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  expression:
    params: [100, -2, 2] # Expression parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. default : sum(nX)==100
    fixed: False # fixed the same expression for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  pose:
    params: [3, 0, 0, 1, 0, 30, 2, -10, 10] # Pose parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. sum(nX)==6 (min, max in degree)
    fixed: False # fixed the same pose for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  texture:
    params: [50, -2, 2] # Texture parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. default : sum(nX)==50, maximum : 200 (increase memory used)
    fixed: False # fixed the same texture for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  neck:
    params: [3, -30, 30] # Neck parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. sum(nX)==3 (min, max in degree)
    fixed: False # fixed the same neck for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  eye:
    params: [6, 0, 0] # Eye parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. sum(nX)==6
    fixed: False # fixed the same eye for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  camera:
    default: [10., 0., 0., -2., 0., 0., 0.] # default camera (type:default) for renderer [fov, tx, ty, tz, rx, ry, rz] (rotation in degree)
    params: [1, 8, 12, 2, -0.05, 0.05, 1, -2.1, -1.9, 3, -30, 30] # Camera parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. sum(nX)==7, (default : [fov, tx, ty, tz, rx, ry, rz], vector : [fov, lookAtX, lookAtY, lookAtZ, radius, phi, theta])
    fixed: False # fixed the same cameras for all visage generated
    type: default # camera type used for renderer (change utilisation of camera parameter) [default, vector]
    animation:
      keyframes: 2 # Number of keyframe
  ambient:
    params: [3, 0.75, 1, 1, 0, 1] # Ambient light parameter intervals. Format: [n1,min1,max1,n2,min2,max2,...]. default : sum(nX)==4, [R,G,B,Intensity]
    fixed: False # fixed the same ambient light for all visage generated
    animation:
      keyframes: 2 # Number of keyframe
  coords_multiplier: 1 # multiply coordinates by the value. (fov must be augmented for not change result in png)

flame:
  face_contour: True # use face contour for generate visage
  translation_3D: True # use 3D translation for generate visage
  model_path: ./model/flame2023.pkl # path for access flame model
  static_landmark_embedding_path: ./model/flame_static_embedding.pkl # path for static landmark embedding file
  dynamic_landmark_embedding_path: ./model/flame_dynamic_embedding.npy # path for dynamic landmark embedding file

save:
  global_:
    outdir: 'output' # path directory for output
    img_resolution: [512, 512] # resolution of image
    random_bg: False # enable random background color for renderer
    show_window: False # show window during save png (enable if images is the screenshot or full black)
    vertical_flip: True # vertical flip for saving image
  obj:
    target: 'ObjSaver'
    enable: False # save into file obj
    location: '/obj'
  png:
    target: 'FaceSaver'
    enable: True # save into file png
    location: '/png/default'
  seg:
    target: 'SegSaver'
    enable: False # save segmentation into file png
    location: '/png/seg'
  video:
    target: 'VideoSaver'
    enable: False
    location: '/mp4'
    fps: 24
  latents:
    target: 'LatentsSaver'
    enable: False # save latents into file npy
    location: '/latents'
  depth:
    target: 'DepthSaver'
    enable: False # save depth into png file
    location: '/png/depth'
    alpha: False # save depth to channel alpha
  lmks3D:
    target: 'Lmks3DSaver'
    enable: False # save landmarks 3D into file npy
    location: '/lmks/3D'
  lmks2D:
    target: 'Lmks2DSaver'
    enable: False
    location: '/lmks/2D'
    npy: False # save landmarks 2D into file npy
    pts: False # save landmarks 2D into file pts
    png: False # save landmarks 2D into file png
    with_visage: False
    use_alpha: True # save landmarks 2D to channel alpha ('png: True' is required)
  markers3D:
    target: 'Markers3DSaver'
    enable: False # save markers 3D into npy file
    location: '/markers/3D'
  markers2D:
    target: 'Markers2DSaver'
    enable: False
    location: '/markers/2D'
    npy: False # save markers 2D into npy file
    pts: False # save markers 2D into pts file
    png: False # save markers 2D into png file
    with_visage: False
    use_alpha: True # save markers 2D to channel alpha ('png: True' is required)
  camera_default:
    target: 'CameraDefaultSaver'
    enable: False
    location: '/camera/default'
  camera_matrices:
    target: 'CameraMatrixSaver'
    enable: False
    location: '/camera/matrices'
  camera_json:
    target: 'CameraJSONSaver'
    enable: False
    location: '/camera'
  density:
    target: 'DensityCubeSaver'
    enable: False # save density cube
    location: '/density_cube'
    size: 64 # size of density cube
    vertices_interval: 0 # interval of vertices used for scaled vertices to density cube size. if 0 then vertices.max() is used
    pts_batch_size: 10000 # number of points process simultaneously for get triangle nearest in density cube process
    method_pts_in_tri: barycentric # method used for check if voxel inside triangle ("barycentric", "normal")
    epsilon_scale: 0.005 # epsilon scale used for calcul epsilon used in method voxel inside triangle. (epsilon = cube_size * epsilon_scale)
    voxel_bits: 8 # Number of bits used for storage voxel
    quantile: 0.9 # Quantile used for ignored many value
    cube_format: cube # the format of density cube (cube or mrc). (format cube, reduce space used but not loaded by USCF ChimeraX)
