save:
  obj:
    enable: True # save into file obj
  png:
    enable: True # save into file png
  video:
    enable: True
  latents:
    enable: True # save latents into file npy
  depth:
    enable: True # save depth into png file
  lmks3D:
    enable: True # save landmarks 3D into file npy
  lmks2D:
    enable: True
    npy: True
    pts: True
    png: True
    with_visage: True
    use_alpha: False
  markers3D:
    enable: True # save markers 3D into npy file
  markers2D:
    enable: True
    npy: True
    pts: True
    png: True
    with_visage: False
  camera_default:
    enable: True
  camera_matrices:
    enable: True
  camera_json:
    enable: True
  density:
    enable: True # save density cube